### PR TITLE
Remove ignored files from source control

### PR DESCRIPTION
**Pull request by azemoh**
These files are ignored  in the `.gitignore` file and rightly so, but somehow they got added to the repository.

They are IDE specific files that are generated by Android Studio and are only relevant to Android Studio. see https://github.com/github/gitignore/blob/master/Global/JetBrains.gitignore

### CODE REVIEW

**Comment by azemoh** [comment]
**Running `git status` after opening the project in Android studio without making any changes**
ignore

**Comment by efemoney** [comment]
Hello @azemoh. Did you manually remove these files? Asking to know because it will be preferred if the all the files are removed and re-added according to the `.gitignore` rules.

**Comment by azemoh** [comment]
Yes I just deleted them and committed the changes. They were later generated by the IDE but doesn't show up in `git status`

**Comment by efemoney** [comment]
Yeah, I have a slight problem with that. Just to ensure that all of the files specified in the `.gitignore` are ignored, can you do a git remove all **on your remote branch** (but keep the local files) and then a git add (that takes into consideration the gitignore file).

**Comment by azemoh** [comment]
Alright, I'll just close this.

**Pull request closed without merging**
